version: '3.8'

services:
  mongo:
    image: mongo:7
    container_name: hotel_mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build: .
    container_name: hotel_backend
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    environment:
      SPRING_DATA_MONGODB_URI: "mongodb://mongo:27017/hotelman"

  frontend:
    build: ./frontend
    container_name: hotel_frontend
    depends_on:
      - backend
    ports:
      - "4200:80"
    environment:
      API_URL: http://backend:8080

volumes:
  mongo_data: